// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chord.proto

#ifndef PROTOBUF_chord_2eproto__INCLUDED
#define PROTOBUF_chord_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace chord {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_chord_2eproto();
void protobuf_AssignDesc_chord_2eproto();
void protobuf_ShutdownFile_chord_2eproto();

class m_int;
class m_node_t;
class m_node_t_int;
class m_node_t_node_t_int;
class m_void;

// ===================================================================

class m_void : public ::google::protobuf::Message {
 public:
  m_void();
  virtual ~m_void();

  m_void(const m_void& from);

  inline m_void& operator=(const m_void& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const m_void& default_instance();

  void Swap(m_void* other);

  // implements Message ----------------------------------------------

  inline m_void* New() const { return New(NULL); }

  m_void* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const m_void& from);
  void MergeFrom(const m_void& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(m_void* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:chord.m_void)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_chord_2eproto();
  friend void protobuf_AssignDesc_chord_2eproto();
  friend void protobuf_ShutdownFile_chord_2eproto();

  void InitAsDefaultInstance();
  static m_void* default_instance_;
};
// -------------------------------------------------------------------

class m_int : public ::google::protobuf::Message {
 public:
  m_int();
  virtual ~m_int();

  m_int(const m_int& from);

  inline m_int& operator=(const m_int& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const m_int& default_instance();

  void Swap(m_int* other);

  // implements Message ----------------------------------------------

  inline m_int* New() const { return New(NULL); }

  m_int* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const m_int& from);
  void MergeFrom(const m_int& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(m_int* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:chord.m_int)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_chord_2eproto();
  friend void protobuf_AssignDesc_chord_2eproto();
  friend void protobuf_ShutdownFile_chord_2eproto();

  void InitAsDefaultInstance();
  static m_int* default_instance_;
};
// -------------------------------------------------------------------

class m_node_t : public ::google::protobuf::Message {
 public:
  m_node_t();
  virtual ~m_node_t();

  m_node_t(const m_node_t& from);

  inline m_node_t& operator=(const m_node_t& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const m_node_t& default_instance();

  void Swap(m_node_t* other);

  // implements Message ----------------------------------------------

  inline m_node_t* New() const { return New(NULL); }

  m_node_t* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const m_node_t& from);
  void MergeFrom(const m_node_t& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(m_node_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string hostname = 1;
  void clear_hostname();
  static const int kHostnameFieldNumber = 1;
  const ::std::string& hostname() const;
  void set_hostname(const ::std::string& value);
  void set_hostname(const char* value);
  void set_hostname(const char* value, size_t size);
  ::std::string* mutable_hostname();
  ::std::string* release_hostname();
  void set_allocated_hostname(::std::string* hostname);

  // optional int64 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // optional int32 portno = 3;
  void clear_portno();
  static const int kPortnoFieldNumber = 3;
  ::google::protobuf::int32 portno() const;
  void set_portno(::google::protobuf::int32 value);

  // optional string machine_name = 4;
  void clear_machine_name();
  static const int kMachineNameFieldNumber = 4;
  const ::std::string& machine_name() const;
  void set_machine_name(const ::std::string& value);
  void set_machine_name(const char* value);
  void set_machine_name(const char* value, size_t size);
  ::std::string* mutable_machine_name();
  ::std::string* release_machine_name();
  void set_allocated_machine_name(::std::string* machine_name);

  // @@protoc_insertion_point(class_scope:chord.m_node_t)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr hostname_;
  ::google::protobuf::int64 id_;
  ::google::protobuf::internal::ArenaStringPtr machine_name_;
  ::google::protobuf::int32 portno_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_chord_2eproto();
  friend void protobuf_AssignDesc_chord_2eproto();
  friend void protobuf_ShutdownFile_chord_2eproto();

  void InitAsDefaultInstance();
  static m_node_t* default_instance_;
};
// -------------------------------------------------------------------

class m_node_t_int : public ::google::protobuf::Message {
 public:
  m_node_t_int();
  virtual ~m_node_t_int();

  m_node_t_int(const m_node_t_int& from);

  inline m_node_t_int& operator=(const m_node_t_int& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const m_node_t_int& default_instance();

  void Swap(m_node_t_int* other);

  // implements Message ----------------------------------------------

  inline m_node_t_int* New() const { return New(NULL); }

  m_node_t_int* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const m_node_t_int& from);
  void MergeFrom(const m_node_t_int& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(m_node_t_int* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .chord.m_node_t node = 1;
  bool has_node() const;
  void clear_node();
  static const int kNodeFieldNumber = 1;
  const ::chord::m_node_t& node() const;
  ::chord::m_node_t* mutable_node();
  ::chord::m_node_t* release_node();
  void set_allocated_node(::chord::m_node_t* node);

  // optional int64 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:chord.m_node_t_int)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::chord::m_node_t* node_;
  ::google::protobuf::int64 id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_chord_2eproto();
  friend void protobuf_AssignDesc_chord_2eproto();
  friend void protobuf_ShutdownFile_chord_2eproto();

  void InitAsDefaultInstance();
  static m_node_t_int* default_instance_;
};
// -------------------------------------------------------------------

class m_node_t_node_t_int : public ::google::protobuf::Message {
 public:
  m_node_t_node_t_int();
  virtual ~m_node_t_node_t_int();

  m_node_t_node_t_int(const m_node_t_node_t_int& from);

  inline m_node_t_node_t_int& operator=(const m_node_t_node_t_int& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const m_node_t_node_t_int& default_instance();

  void Swap(m_node_t_node_t_int* other);

  // implements Message ----------------------------------------------

  inline m_node_t_node_t_int* New() const { return New(NULL); }

  m_node_t_node_t_int* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const m_node_t_node_t_int& from);
  void MergeFrom(const m_node_t_node_t_int& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(m_node_t_node_t_int* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .chord.m_node_t node_1 = 1;
  bool has_node_1() const;
  void clear_node_1();
  static const int kNode1FieldNumber = 1;
  const ::chord::m_node_t& node_1() const;
  ::chord::m_node_t* mutable_node_1();
  ::chord::m_node_t* release_node_1();
  void set_allocated_node_1(::chord::m_node_t* node_1);

  // optional .chord.m_node_t node_2 = 2;
  bool has_node_2() const;
  void clear_node_2();
  static const int kNode2FieldNumber = 2;
  const ::chord::m_node_t& node_2() const;
  ::chord::m_node_t* mutable_node_2();
  ::chord::m_node_t* release_node_2();
  void set_allocated_node_2(::chord::m_node_t* node_2);

  // optional int64 id = 3;
  void clear_id();
  static const int kIdFieldNumber = 3;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:chord.m_node_t_node_t_int)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::chord::m_node_t* node_1_;
  ::chord::m_node_t* node_2_;
  ::google::protobuf::int64 id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_chord_2eproto();
  friend void protobuf_AssignDesc_chord_2eproto();
  friend void protobuf_ShutdownFile_chord_2eproto();

  void InitAsDefaultInstance();
  static m_node_t_node_t_int* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// m_void

// -------------------------------------------------------------------

// m_int

// optional int64 id = 1;
inline void m_int::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 m_int::id() const {
  // @@protoc_insertion_point(field_get:chord.m_int.id)
  return id_;
}
inline void m_int::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:chord.m_int.id)
}

// -------------------------------------------------------------------

// m_node_t

// optional string hostname = 1;
inline void m_node_t::clear_hostname() {
  hostname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& m_node_t::hostname() const {
  // @@protoc_insertion_point(field_get:chord.m_node_t.hostname)
  return hostname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void m_node_t::set_hostname(const ::std::string& value) {
  
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:chord.m_node_t.hostname)
}
inline void m_node_t::set_hostname(const char* value) {
  
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:chord.m_node_t.hostname)
}
inline void m_node_t::set_hostname(const char* value, size_t size) {
  
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:chord.m_node_t.hostname)
}
inline ::std::string* m_node_t::mutable_hostname() {
  
  // @@protoc_insertion_point(field_mutable:chord.m_node_t.hostname)
  return hostname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* m_node_t::release_hostname() {
  
  return hostname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void m_node_t::set_allocated_hostname(::std::string* hostname) {
  if (hostname != NULL) {
    
  } else {
    
  }
  hostname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hostname);
  // @@protoc_insertion_point(field_set_allocated:chord.m_node_t.hostname)
}

// optional int64 id = 2;
inline void m_node_t::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 m_node_t::id() const {
  // @@protoc_insertion_point(field_get:chord.m_node_t.id)
  return id_;
}
inline void m_node_t::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:chord.m_node_t.id)
}

// optional int32 portno = 3;
inline void m_node_t::clear_portno() {
  portno_ = 0;
}
inline ::google::protobuf::int32 m_node_t::portno() const {
  // @@protoc_insertion_point(field_get:chord.m_node_t.portno)
  return portno_;
}
inline void m_node_t::set_portno(::google::protobuf::int32 value) {
  
  portno_ = value;
  // @@protoc_insertion_point(field_set:chord.m_node_t.portno)
}

// optional string machine_name = 4;
inline void m_node_t::clear_machine_name() {
  machine_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& m_node_t::machine_name() const {
  // @@protoc_insertion_point(field_get:chord.m_node_t.machine_name)
  return machine_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void m_node_t::set_machine_name(const ::std::string& value) {
  
  machine_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:chord.m_node_t.machine_name)
}
inline void m_node_t::set_machine_name(const char* value) {
  
  machine_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:chord.m_node_t.machine_name)
}
inline void m_node_t::set_machine_name(const char* value, size_t size) {
  
  machine_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:chord.m_node_t.machine_name)
}
inline ::std::string* m_node_t::mutable_machine_name() {
  
  // @@protoc_insertion_point(field_mutable:chord.m_node_t.machine_name)
  return machine_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* m_node_t::release_machine_name() {
  
  return machine_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void m_node_t::set_allocated_machine_name(::std::string* machine_name) {
  if (machine_name != NULL) {
    
  } else {
    
  }
  machine_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), machine_name);
  // @@protoc_insertion_point(field_set_allocated:chord.m_node_t.machine_name)
}

// -------------------------------------------------------------------

// m_node_t_int

// optional .chord.m_node_t node = 1;
inline bool m_node_t_int::has_node() const {
  return !_is_default_instance_ && node_ != NULL;
}
inline void m_node_t_int::clear_node() {
  if (GetArenaNoVirtual() == NULL && node_ != NULL) delete node_;
  node_ = NULL;
}
inline const ::chord::m_node_t& m_node_t_int::node() const {
  // @@protoc_insertion_point(field_get:chord.m_node_t_int.node)
  return node_ != NULL ? *node_ : *default_instance_->node_;
}
inline ::chord::m_node_t* m_node_t_int::mutable_node() {
  
  if (node_ == NULL) {
    node_ = new ::chord::m_node_t;
  }
  // @@protoc_insertion_point(field_mutable:chord.m_node_t_int.node)
  return node_;
}
inline ::chord::m_node_t* m_node_t_int::release_node() {
  
  ::chord::m_node_t* temp = node_;
  node_ = NULL;
  return temp;
}
inline void m_node_t_int::set_allocated_node(::chord::m_node_t* node) {
  delete node_;
  node_ = node;
  if (node) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:chord.m_node_t_int.node)
}

// optional int64 id = 2;
inline void m_node_t_int::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 m_node_t_int::id() const {
  // @@protoc_insertion_point(field_get:chord.m_node_t_int.id)
  return id_;
}
inline void m_node_t_int::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:chord.m_node_t_int.id)
}

// -------------------------------------------------------------------

// m_node_t_node_t_int

// optional .chord.m_node_t node_1 = 1;
inline bool m_node_t_node_t_int::has_node_1() const {
  return !_is_default_instance_ && node_1_ != NULL;
}
inline void m_node_t_node_t_int::clear_node_1() {
  if (GetArenaNoVirtual() == NULL && node_1_ != NULL) delete node_1_;
  node_1_ = NULL;
}
inline const ::chord::m_node_t& m_node_t_node_t_int::node_1() const {
  // @@protoc_insertion_point(field_get:chord.m_node_t_node_t_int.node_1)
  return node_1_ != NULL ? *node_1_ : *default_instance_->node_1_;
}
inline ::chord::m_node_t* m_node_t_node_t_int::mutable_node_1() {
  
  if (node_1_ == NULL) {
    node_1_ = new ::chord::m_node_t;
  }
  // @@protoc_insertion_point(field_mutable:chord.m_node_t_node_t_int.node_1)
  return node_1_;
}
inline ::chord::m_node_t* m_node_t_node_t_int::release_node_1() {
  
  ::chord::m_node_t* temp = node_1_;
  node_1_ = NULL;
  return temp;
}
inline void m_node_t_node_t_int::set_allocated_node_1(::chord::m_node_t* node_1) {
  delete node_1_;
  node_1_ = node_1;
  if (node_1) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:chord.m_node_t_node_t_int.node_1)
}

// optional .chord.m_node_t node_2 = 2;
inline bool m_node_t_node_t_int::has_node_2() const {
  return !_is_default_instance_ && node_2_ != NULL;
}
inline void m_node_t_node_t_int::clear_node_2() {
  if (GetArenaNoVirtual() == NULL && node_2_ != NULL) delete node_2_;
  node_2_ = NULL;
}
inline const ::chord::m_node_t& m_node_t_node_t_int::node_2() const {
  // @@protoc_insertion_point(field_get:chord.m_node_t_node_t_int.node_2)
  return node_2_ != NULL ? *node_2_ : *default_instance_->node_2_;
}
inline ::chord::m_node_t* m_node_t_node_t_int::mutable_node_2() {
  
  if (node_2_ == NULL) {
    node_2_ = new ::chord::m_node_t;
  }
  // @@protoc_insertion_point(field_mutable:chord.m_node_t_node_t_int.node_2)
  return node_2_;
}
inline ::chord::m_node_t* m_node_t_node_t_int::release_node_2() {
  
  ::chord::m_node_t* temp = node_2_;
  node_2_ = NULL;
  return temp;
}
inline void m_node_t_node_t_int::set_allocated_node_2(::chord::m_node_t* node_2) {
  delete node_2_;
  node_2_ = node_2;
  if (node_2) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:chord.m_node_t_node_t_int.node_2)
}

// optional int64 id = 3;
inline void m_node_t_node_t_int::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 m_node_t_node_t_int::id() const {
  // @@protoc_insertion_point(field_get:chord.m_node_t_node_t_int.id)
  return id_;
}
inline void m_node_t_node_t_int::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:chord.m_node_t_node_t_int.id)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace chord

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_chord_2eproto__INCLUDED
